formatter: "markdown"

header-from: ".config/header.md"

output:
  file: "README.md"

sort:
  enabled: true
  by: required

settings:
  read-comments: false
  hide-empty: true
  escape: false

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Modules }}

  ## Usage

  ```hcl
  {{ include ".config/example.tf" }}
  ```

  > Important! For simplicity, the examples do not point to a
  > specific version of the module. For a production deployment,
  > it is suggested that you point to a specific version tag like:
  >
  > **source = "git@github.com:renaiss-io/terraform-aws-odoo.git?ref=v1.0.0"**

  {{ .Inputs }}

  {{ .Outputs }}
