formatter: "markdown"

header-from: ".config/header.md"

output:
  file: "README.md"

sort:
  enabled: true
  by: required

settings:
  read-comments: false
  hide-empty: true
  escape: false

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Modules }}

  ## Usage

  ```hcl
  {{ include ".config/example.tf" }}
  ```


  {{ .Inputs }}

  {{ .Outputs }}
